channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - opencv
  - matplotlib
  - scanpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow==2.4.1
  - tqdm
  - pip:
    - alphashape==1.3.1
    - shapely==1.7.1
    - squidpy==1.1.2
    - scanpy
    - descartes==1.1.0